
server:
  port: 2222

eureka:
  instance:
  # hostname: localhost
  prefer-ip-address: false
  #  instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  cloud:
    config:
      uri: http://localhost:8020/
      profile: default
      label: master

