server:
  port: 6666

eureka:
  instance:
  # hostname: localhost
  prefer-ip-address: false
  #  instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
  #  instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 是否与服务发现组件进行结合,设为true开启通过服务中心的自动根据 serviceId 创建路由的功能






