server:
  port: 9999

eureka:
  instance:
  # hostname: localhost
  prefer-ip-address: false
  #  instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
  #  instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/


