server:
  port: 1111
spring:
  application:
    name: register-center
# ???????? eureka ????????????????,?????????,??????????????
eureka:
  client:
    fetch-registry: false # ????????????
    register-with-eureka: false # ??????Eureka Server????????,???????????????????????????
  serviceUrl:
    defaultZone: http://localhost:1111/eureka/
